# Generated by Django 4.0.5 on 2022-06-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ('-published',), 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
